### ISSUE TITLE
AdminLTE Select2 插件显示样式异常

### ISSUE THREAD

**Issue by drodata** [drodata/yii2-utility#1]
![select2-bug](https://cloud.githubusercontent.com/assets/5827655/19543977/ec4cd948-96ad-11e6-802c-d6520598ebd6.png)

可以看到显示的 option 值没有上下居中，有点偏上。此效果在 AdminLTE.css 内设置：

``` css
.select2-container .select2-selection--single .select2-selection__rendered {
  padding-left: 0;
  padding-right: 0;
  height: auto;
  margin-top: -4px; /* !*/
}
```

https://github.com/almasaeed2010/AdminLTE/blob/master/dist/css/AdminLTE.css#L4239

原因未知。
